title: Blog de Antonio Jiménez
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Antonio Jiménez # add your name
author-img: Antonio@2x.jpg # add your photo
about-author: Me llamo Antonio Jiménez y soy desarrollador certificado en Magento 2 # add description
social-twitter: n0nio # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: n0ni0 # add your Github handle
social-linkedin: ajimenezvelazquez # add your Linkedin handle
social-email: ajimenez.bf@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
